spring:
  application:
    name: Product
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/spendless-product
    username: postgres
    password: Souvikp683@
#    password: vyrazu
    driver-class-name: org.postgresql.Driver
  output:
    ansi:
      enabled: ALWAYS
  devtools:
    restart:
      enabled: true

server:
  port: 8009
  error:
    include-binding-errors: always

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /docs
    enabled: true
  override-with-generic-response: false

access-token-expiration: 86400000
refresh-token-expiration: 2592000000
jwt-secret-key: dsamdnash32qw903u0riowqejoirj3290roijaskflnlksznfklnsanfasf

