spring:
  application:
    name: Product
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/spendless-product
    username: postgres
    password: vyrazu
    driver-class-name: org.postgresql.Driver
server:
  port: 8009