name: CI/CD to Render

on:
  push:
    branches:
      - develop   # change if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Project
        run: mvnw clean package -DskipTests

      - name: Trigger Render Deploy
        run: |
          echo "Triggering Render Deploy..."
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }} -w "\nStatus: %{http_code}\n"